framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%?auto_setup=true'
                options:
                    exchange:
                        name: x_pass_async
                        type: direct
                    queues:
                        q_pass_async: ~
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: pass_failed.topic
                        type: topic

            sync: 'sync://'

        routing:
            # Route your messages to the transports
             'App\Message\ImportFilePostcodeCommand': async

when@test:
  framework:
      messenger:
          transports:
              # replace with your transport name here (e.g., my_transport: 'in-memory://')
              # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
              async: 'in-memory://'
