version: '3'

networks:
  passenger_test:

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: passenger-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
    networks:
      - passenger_test

  php82-service:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: passenger-php
    restart: on-failure
    depends_on:
      - mysql-service
      - postgres-service
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - passenger_test

  mysql-service:
    image: mysql:8.0
    container_name: passenger-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "4306:3306"
    volumes:
      - ./var/data/mysql:/var/lib/mysql
    networks:
      - passenger_test

  postgres-service:
    image: postgis/postgis:16-3.4-alpine
    container_name: passenger-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-passenger}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    ports:
      - '6432:5432'
    volumes:
      - ./var/data/psql:/var/lib/postgresql/data:rw
    networks:
      - passenger_test

  messenger-consumer-1:
    build:
      context: .
      dockerfile: ./.docker/php-cli/Dockerfile
    container_name: messenger-consumer-1
    restart: on-failure
    command: php -dmemory_limit=-1 bin/console messenger:consume -vv
    volumes:
      - ./:/var/www/project
    depends_on:
      - php82-service
      - postgres-service
    networks:
      - passenger_test

  messenger-consumer-2:
    build:
      context: .
      dockerfile: ./.docker/php-cli/Dockerfile
    container_name: messenger-consumer-2
    restart: on-failure
    command: php -dmemory_limit=-1 bin/console messenger:consume -vv
    volumes:
      - ./:/var/www/project
    depends_on:
      - php82-service
      - postgres-service
    networks:
      - passenger_test