version: '3'

networks:
  passenger_test:

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: passenger-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
    networks:
      - passenger_test

  php82-service:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: passenger-php
    restart: on-failure
    depends_on:
      - postgres-service
    ports:
      - "9000"
    volumes:
      - ./:/var/www/project
    networks:
      - passenger_test

  postgres-service:
    image: postgis/postgis:16-3.4-alpine
    container_name: passenger-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-passenger}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    ports:
      - '6432:5432'
    volumes:
      - ./var/data/psql:/var/lib/postgresql/data:rw
    networks:
      - passenger_test

  rabbitmq-service: # The RabbitMQ container.
    image: "rabbitmq:3.12-management-alpine"
    container_name: passenger-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./var/data/rabbitmq:/var/lib/rabbitmq
    networks:
      - passenger_test

  messenger-consumer-1:
    build:
      context: .
      dockerfile: ./.docker/php-cli/Dockerfile
    container_name: messenger-consumer-1
    restart: always
    command: php -dmemory_limit=-1 bin/console messenger:consume async -vv
    volumes:
      - ./:/var/www/project
    depends_on:
      - php82-service
      - postgres-service
    networks:
      - passenger_test

  messenger-consumer-2:
    build:
      context: .
      dockerfile: ./.docker/php-cli/Dockerfile
    container_name: messenger-consumer-2
    restart: always
    command: php -dmemory_limit=-1 bin/console messenger:consume async -vv
    volumes:
      - ./:/var/www/project
    depends_on:
      - php82-service
      - postgres-service
    networks:
      - passenger_test